# -*- coding: utf-8 -*-
"""
Tolerant and secure AI Markdown output parser for ZipToTxt.
Treats AI outputs as untrusted input: sanitizes paths, validates boundaries,
and gracefully heals truncated code fences.
"""
import re
import logging
from typing import Dict, List, Tuple, Optional
from .constants import (
    MAX_AI_INPUT_BYTES,
    MAX_AI_FILES,
    MAX_AI_TOTAL_OUTPUT_BYTES,
    MAX_AI_SINGLE_OUTPUT_BYTES,
)
from .models import SecurityError, ParsedAiBlock, ParseResult
from .security import normalize_ai_path, is_sensitive_path, human_size

logger = logging.getLogger(__name__)

# Markdown headers and code comments specifying file paths
FILE_HEADER_PATTERNS = [
    re.compile(r'^\s*(?:#{1,6}\s*)?FILE\s*:\s*[`"\']?(.+?)[`"\']?\s*$', re.IGNORECASE),
    re.compile(r'^\s*\*\*(?:FILE|File|FilePath|Path)\s*:\s*\*\*\s*[`"\']?(.+?)[`"\']?\s*$', re.IGNORECASE),
    re.compile(r'^\s*\*\*(?:FILE|File|FilePath|Path)\s*:\s*[`"\']?(.+?)[`"\']?\*\*\s*$', re.IGNORECASE),
    re.compile(r'^\s*(?://|/\*|<!--|#)\s*(?:FILE|File|FilePath)\s*:\s*[`"\']?(.+?)[`"\']?(?:\s*\*/|\s*-->)?\s*$', re.IGNORECASE),
    re.compile(r'^\s*\[\s*(?:FILE|File|FilePath)(?:\s*:)?\s*[`"\']?(.+?)[`"\']?\s*\]\s*$', re.IGNORECASE),
    re.compile(r'^\s*(?:FilePath|File Path|Target File|File)\s*:\s*[`"\']?(.+?)[`"\']?\s*$', re.IGNORECASE),
]

INLINE_FENCE_PATTERN = re.compile(
    r'^\s*```(?:[A-Za-z0-9_+.#-]+)?(?:\s+|:)(?:file=|path=)?["\'`]?([A-Za-z0-9_./\\-]+)["\'`]?\s*$',
    re.IGNORECASE
)
STANDARD_FENCE_START = re.compile(r'^\s*```(?:[A-Za-z0-9_+.#-]+)?\s*$')
FENCE_END = re.compile(r'^\s*```\s*$')

def parse_ai_output(raw_text: str) -> Tuple[Dict[str, str], List[str], int]:
    """
    Parses Markdown text generated by LLMs to extract file paths and contents.
    Returns: (files_dict, warnings_list, auto_closed_count)
    """
    if not raw_text or not raw_text.strip():
        raise ValueError("AI input text is empty.")

    raw_bytes = raw_text.encode('utf-8', errors='replace')
    if len(raw_bytes) > MAX_AI_INPUT_BYTES:
        raise SecurityError(f"AI input payload size ({human_size(len(raw_bytes))}) exceeds limit {human_size(MAX_AI_INPUT_BYTES)}")

    lines = raw_text.replace('\r\n', '\n').replace('\r', '\n').split('\n')
    warnings: List[str] = []
    raw_blocks: List[Tuple[str, str, Optional[str], bool]] = []

    current_path: Optional[str] = None
    detected_lang: Optional[str] = None
    buffer: List[str] = []
    in_code_block = False
    auto_closed_count = 0

    def flush_block(is_auto_closed: bool = False):
        nonlocal current_path, detected_lang, buffer, in_code_block, auto_closed_count
        if current_path is not None:
            content = "\n".join(buffer)
            content_bytes_len = len(content.encode('utf-8', errors='replace'))
            if content_bytes_len > MAX_AI_SINGLE_OUTPUT_BYTES:
                raise SecurityError(f"Single file content size exceeds limit: {current_path} ({human_size(content_bytes_len)})")
            raw_blocks.append((current_path, content, detected_lang, is_auto_closed))
            if is_auto_closed:
                auto_closed_count += 1
                warnings.append(f"File [{current_path}] code fence was unclosed and has been auto-healed.")
        current_path = None
        buffer = []
        in_code_block = False
        detected_lang = None

    for line in lines:
        if not in_code_block:
            # Check for inline fence syntax: ```python:src/main.py
            inline_match = INLINE_FENCE_PATTERN.match(line)
            if inline_match and '.' in inline_match.group(1):
                try:
                    norm = normalize_ai_path(inline_match.group(1))
                    current_path = norm
                    lang_part = line.strip().lstrip('`').split(':')[0].split()[0]
                    detected_lang = lang_part if lang_part else None
                    in_code_block = True
                    continue
                except SecurityError:
                    pass

            # Check header patterns
            matched_path: Optional[str] = None
            for pattern in FILE_HEADER_PATTERNS:
                m = pattern.match(line)
                if m and m.group(1):
                    cand = m.group(1).strip()
                    if cand and not cand.startswith('http') and '://' not in cand:
                        try:
                            matched_path = normalize_ai_path(cand)
                            break
                        except SecurityError:
                            pass

            if matched_path:
                current_path = matched_path
                continue

            if current_path is not None:
                if STANDARD_FENCE_START.match(line):
                    lang = line.strip().lstrip('`').strip()
                    detected_lang = lang if lang else None
                    in_code_block = True
                    continue
                continue

            continue

        # In code block
        if FENCE_END.match(line):
            flush_block(False)
        else:
            buffer.append(line)

    # Handle truncated output where AI ran out of tokens while still inside a code fence
    if in_code_block and current_path is not None:
        flush_block(True)

    if not raw_blocks:
        raise ValueError("No valid file code blocks found in AI response text.")

    # Merge partitioned blocks
    merged_map: Dict[str, str] = {}
    for path, content, _, _ in raw_blocks:
        if path in merged_map:
            merged_map[path] = merged_map[path] + "\n" + content
        else:
            merged_map[path] = content

    if len(merged_map) > MAX_AI_FILES:
        raise SecurityError(f"Number of parsed files ({len(merged_map)}) exceeds maximum limit {MAX_AI_FILES}")

    total_bytes = sum(len(c.encode('utf-8', errors='replace')) for c in merged_map.values())
    if total_bytes > MAX_AI_TOTAL_OUTPUT_BYTES:
        raise SecurityError(f"Total parsed output size ({human_size(total_bytes)}) exceeds limit {human_size(MAX_AI_TOTAL_OUTPUT_BYTES)}")

    return merged_map, warnings, auto_closed_count

def parse_ai_blocks(raw_text: str) -> Dict[str, str]:
    """Convenience facade returning just the dictionary of parsed files."""
    files_map, _, _ = parse_ai_output(raw_text)
    return files_map
